# Generated by Django 5.1.2 on 2025-11-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', '📝 Pending'), ('shortlisted', '⭐ Shortlisted'), ('rejected', '❌ Rejected'), ('accepted', '✅ Accepted')], default='pending', max_length=50),
        ),
    ]
