# Generated by Django 5.1.2 on 2025-09-22 17:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-applied_at'], 'verbose_name': 'Job Application', 'verbose_name_plural': 'Job Applications'},
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='current_company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Current Company'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='current_position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Current Position'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='github_profile',
            field=models.URLField(blank=True, verbose_name='GitHub Profile'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this application'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('referral', 'Employee Referral'), ('other', 'Other')], default='website', max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(help_text='Why are you interested in this position?', verbose_name='Cover Letter'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job.job'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(help_text='Upload your resume (PDF)', upload_to='resumes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', '📝 Pending'), ('reviewed', '👀 Reviewed'), ('shortlisted', '⭐ Shortlisted'), ('interview', '💼 Interview'), ('rejected', '❌ Rejected'), ('accepted', '✅ Accepted')], default='pending', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'applicant_email')},
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status', 'applied_at'], name='job_jobappl_status_931e91_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applicant_email'], name='job_jobappl_applica_56f54d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='job_jobappl_job_id_168928_idx'),
        ),
    ]
