# Generated by Django 5.1.2 on 2025-09-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='short_description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
