# Generated by Django 5.1.2 on 2025-09-23 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_short_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this job opportunity', null=True)),
                ('category', models.CharField(choices=[('interested', 'Interested'), ('applying_soon', 'Applying Soon'), ('research', 'Need to Research'), ('comparison', 'For Comparison'), ('favorite', 'Favorite')], default='interested', max_length=20)),
                ('reminder_date', models.DateTimeField(blank=True, help_text='Set a reminder for this job', null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='job.job')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Job',
                'verbose_name_plural': 'Saved Jobs',
                'ordering': ['-saved_at'],
                'unique_together': {('job_seeker', 'job')},
            },
        ),
    ]
