# Generated by Django 5.1.2 on 2025-09-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_savedjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='source',
        ),
    ]
