# Generated by Django 5.1.2 on 2025-10-09 07:38

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_jobapplication_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(help_text='Main about us image (recommended: 800x600px)', upload_to='about/us/')),
                ('mission', ckeditor.fields.RichTextField(help_text='Company mission statement')),
                ('vision', ckeditor.fields.RichTextField(help_text='Company vision statement')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='CompanyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('bi-people', 'Teamwork'), ('bi-lightbulb', 'Innovation'), ('bi-shield-check', 'Integrity'), ('bi-heart', 'Passion'), ('bi-award', 'Excellence'), ('bi-graph-up', 'Growth'), ('bi-hand-thumbs-up', 'Quality'), ('bi-clock', 'Commitment'), ('bi-globe', 'Global'), ('bi-cup', 'Success')], max_length=50)),
                ('number', models.CharField(help_text='e.g., 100+, 5000, 99%', max_length=50)),
                ('label', models.CharField(help_text='e.g., Projects Completed, Happy Clients', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='job.aboutus')),
            ],
            options={
                'verbose_name': 'Company Stat',
                'verbose_name_plural': 'Company Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OurValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('bi-people', 'Teamwork'), ('bi-lightbulb', 'Innovation'), ('bi-shield-check', 'Integrity'), ('bi-heart', 'Passion'), ('bi-award', 'Excellence'), ('bi-graph-up', 'Growth'), ('bi-hand-thumbs-up', 'Quality'), ('bi-clock', 'Commitment'), ('bi-globe', 'Global'), ('bi-cup', 'Success')], help_text='Select an icon for this value', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which values are displayed')),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='job.aboutus')),
            ],
            options={
                'verbose_name': 'Our Value',
                'verbose_name_plural': 'Our Values',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text='Team member photo (recommended: 400x400px)', upload_to='about/team/')),
                ('bio', models.TextField(help_text='Short bio/description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which team members are displayed')),
                ('is_active', models.BooleanField(default=True)),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn Profile')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter Profile')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub Profile')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio Website')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='job.aboutus')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
