# Generated by Django 5.1.2 on 2025-10-09 07:55

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_aboutus_companystat_ourvalue_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='mission',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Company mission statement', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='vision',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Company vision statement', verbose_name='Text'),
        ),
    ]
