# Generated by Django 5.1.2 on 2025-10-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_aboutus_description_alter_aboutus_mission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companystat',
            name='about',
        ),
        migrations.RemoveField(
            model_name='ourvalue',
            name='about',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='about',
        ),
    ]
