# Generated by Django 5.1.2 on 2025-10-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_remove_companystat_about_remove_ourvalue_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(default='We are a passionate team dedicated to delivering exceptional solutions...', help_text='Main about us content'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, help_text='Main about us image (recommended: 800x600px)', null=True, upload_to='about/us/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='mission',
            field=models.TextField(default='To revolutionize the recruitment landscape by creating seamless connections between exceptional talent and forward-thinking companies through innovative technology and personalized human touch.', help_text='Company mission statement'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='About Our Company', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='vision',
            field=models.TextField(default="To become the world's most trusted career ecosystem, where talent and opportunity converge to shape the future of work.", help_text='Company vision statement'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, help_text='Team member photo (recommended: 400x400px)', null=True, upload_to='about/team/'),
        ),
    ]
