# Generated by Django 5.1.2 on 2025-10-09 10:31

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_companystat_is_active_alter_aboutus_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='mission',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='vision',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
