# Generated by Django 5.1.2 on 2025-10-09 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_contactinfo_contactmessage_faq_sitesetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='last_status_change',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last Status Change'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status_change_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status_change_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status_changed_at'], name='job_jobappl_status__3e3c01_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status_change_read'], name='job_jobappl_status__0c97bf_idx'),
        ),
    ]
